### ISSUE TITLE
How to package and install a Payara application  with a MySQL database using Docker on Windows.

### ISSUE THREAD

**Issue by desbenn** [DPBandA/dpba#101]
- [x] Learn [Docker](https://docs.docker.com/docker-hub/quickstart/).
- [x] Packaging and deploying a Payara application with a MySQL database using Docker on Windows involves several steps. Here's a step-by-step guide:

1. **Install Docker:**
   - Download and install Docker Desktop for Windows from the official Docker website: [Docker Desktop for Windows](https://www.docker.com/products/docker-desktop).

2. **Create a Dockerfile for Payara:**
   - Create a new directory for your project and navigate to it in the command prompt or PowerShell.
   - Create a file named `Dockerfile` (without any file extension) and add the following content:

     ```Dockerfile
     # Use the official Payara Server image as the base image
     FROM payara/server-full:latest

     # Copy your Payara application WAR file to the deployments directory
     COPY your-application.war $DEPLOY_DIR

     # Expose the ports your application will use
     EXPOSE 8080 8181

     # (Optional) Set environment variables if needed
     # ENV VAR_NAME VAR_VALUE

     # (Optional) Add any additional configurations or customizations
     # ADD config.xml $PAYARA_PATH/glassfish/domains/domain1/config/
     ```

   - Replace `your-application.war` with the actual name of your Payara application file.

3. **Create Docker Compose file for MySQL:**
   - Create a file named `docker-compose.yml` in the same directory and add the following content:

     ```yaml
     version: '3'
     services:
       mysql:
         image: mysql:latest
         container_name: mysql-container
         environment:
           MYSQL_ROOT_PASSWORD: your-root-password
           MYSQL_DATABASE: your-database-name
           MYSQL_USER: your-username
           MYSQL_PASSWORD: your-password
         ports:
           - "3306:3306"
     ```

   - Replace `your-root-password`, `your-database-name`, `your-username`, and `your-password` with your desired MySQL configurations.

4. **Build Docker Images:**
   - Open a command prompt or PowerShell and navigate to your project directory.
   - Run the following commands to build the Docker images:

     ```bash
     docker build -t payara-app .
     docker-compose up -d
     ```

5. **Verify Containers:**
   - Check if the containers are running:

     ```bash
     docker ps
     ```

   - You should see both the Payara and MySQL containers listed.

6. **Access Payara Application:**
   - Open a web browser and navigate to `http://localhost:8080/your-application-context`, replacing `your-application-context` with the actual context of your Payara application.

That's it! You have successfully packaged and deployed a Payara application with a MySQL database using Docker on Windows. Adjust the configurations and file names according to your project requirements.
